### ISSUE TITLE
fileMode and dirMode must be explicitly given in gradle 1.0 milestone 9

### ISSUE THREAD

**Issue by david-resnick** [TrigonicSolutions/gradle-rpm-plugin#15]
As of milestone 9 the default values for CopySpec.fileMode and CopySpec.dirMode is null (previously the members were ints with defaults of 0644 and 0755).

So as of milestone 9 values must be given for fileMode (and dirMode where createDirectoryEntry=true).

This breaks src/test/groovy/com/trigonic/gradle/plugins/rpm/RpmPluginTest.groovy well because of no default for fileMode (but misses dirMode).

**Comment by AlanKrueger** [comment]
I haven't been able to reproduce this. We're building with Gradle 1.2 and both explicit and implicit fileModes and I don't think we're seeing this issue.
